default: true

MD003:
  style: atx
MD004:
  style: dash
MD007:
  indent: 4
MD013:
  line_length: 120
  code_block_line_length: 120
MD046:
  style: fenced
MD048:
  style: backtick
MD049:
  style: asterisk
MD050:
  style: asterisk
