[project]
name = "maturin-import-hook"
version = "0.1.0"
dependencies = [
    "filelock"
]

[tool.setuptools.packages.find]
where = ["src"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
