blank_issues_enabled: true
contact_links:
  - name: ❓ Question
    url: https://github.com/PyO3/maturin-import-hook/discussions
    about: Ask and answer questions about maturin-import-hook on Discussions
  - name: 🔧 Troubleshooting
    url: https://github.com/PyO3/maturin-import-hook/discussions
    about: For troubleshooting help, see the Discussions
